### ISSUE TITLE
Two horizontal scroll in version ^2.0.0-RC3

### ISSUE THREAD

**Issue by huynhsamha** [marmelab/react-admin#1819]
Hello, I'm using the react-admin version ^2.0.0-RC3, but I get an error on a table with multiple columns with 2 horizontal scroll (in body and table), the following image is my error:

![img](https://user-images.githubusercontent.com/24195776/39912234-499c5aee-5528-11e8-9254-8bd33b2cc6a5.png)

I want only horizontal scroll in table and columns is not stretch, so can you support with options in <Resource>

Thank you.

**Comment by fzaninotto** [comment]
I can reproduce it on Chrome mac with an extension to make the scrollbars visible. However I don't understand what could cause this...

**Comment by fzaninotto** [comment]
I suspect a bug cause by material-ui tooltips, because the (hidden) tooltips are the only element that go beyond the normal body width.

![image](https://user-images.githubusercontent.com/99944/39924795-820d823a-5529-11e8-91fe-ab3efaea6d1c.png)

**Comment by fzaninotto** [comment]
I think it's related to https://github.com/mui-org/material-ui/issues/9362. Do the second scrollbar appear right after loading the page, or only after you resize the browser window?

**Comment by huynhsamha** [comment]
Hello @fzaninotto, I'm using Chrome on Ubuntu.
First, only one scollbar of body on window. After I inspected elements on browser (that also resize the browser window), the second scrollbar appeared as my scnapshot (table has one and body also).

I'd like the toolbar with Add filter, Create and Refresh will be fixed on the top with the title of Resource. Current they is on the right of the table (when I load page or refresh, they can't be seen because it on the right).

**Comment by huynhsamha** [comment]
Hi @fzaninotto,

I current fixed my problem by add some css:
```scss
.layout {
    .list-page {
			table {
					width: 100%;
					overflow: auto;
            th,
            tr {
                span {
                    white-space: nowrap;
                    overflow: hidden;
                    text-overflow: ellipsis;
                }
            }
        }
    }
}

body {
		overflow-x: hidden;
		overflow-y: auto;
}
```

But I'd like the toolbar with Add filter, Create and Search, and Paging appeared fixed on screen, not scroll to right to view
