### ISSUE TITLE
Filters - Cannot read properties of null (reading 'control')

### ISSUE THREAD

**Issue by yousseftarekkh** [marmelab/react-admin#7749]
**What you were expecting:**

Normal filtering for the list

**What happened instead:**
<img width="743" alt="Screen Shot 2022-05-24 at 1 56 14 AM" src="https://user-images.githubusercontent.com/29442110/169922518-bbec3c4e-8ddf-4c1f-a058-200ecb05a620.png">

**Steps to reproduce:**
1. Add a resource
2. Access the list for this resource
3. Modify the `<List />` to contain some `filters`

**Related code:**
```tsx

const postFilters = [
  <TextInput variant="outlined" label="City" source="city" />,
];

<List
    filters={postFilters}
    actions={
      <TopToolbar>
        <FilterButton />
      </TopToolbar>
    }
    sort={{ field: 'created_at', order: 'DESC' }}>
    {...}
</List>
```

**Environment**

* React-admin version: `4.1.0`
* Last version that did not exhibit the issue (if applicable): `3.x`
* React version: `18.1.0`
* Browser: `Chrome`

## NB
Using yarn PnP for this project which might be something related to the issue.

**Comment by yousseftarekkh** [comment]
@fzaninotto I've followed all the documentation explicitly and tried all the possible cases, including the one you suggested, and no it's not working, that's basically why I created an Issue to get more insights about a potential bug. A similar topic was mentioned here https://github.com/marmelab/react-admin/issues/7501. I think there's a problem with the `Form`/`SimpleForm`, or maybe the issue exists in my setup.

### More Info (as labeled)
I need to customize the actions because I need to omit the default `CreateButton` and needed to do something more with it. So I've extracted the logic and included the `FilterButton`

### Tried usecases:
1. Tried the simplest one where we include a `TextInput` inside the `filters` prop and the `List` had the normal `ListActions` (not overriden)
```tsx
<List filters={[<TextInput variant="outlined" placeholder="Example" label="City" source="city" />]} />
```
**Result** - did not work, also shows the `Cannot read properties of null (reading 'control')`

2. Wrapping the `List` from (example n.1) inside a `Form`
```tsx
<Form>
  <List filters={[<TextInput variant="outlined" placeholder="Example" label="City" source="city" 
  />]} />
</Form>
```

**Result** - did not show the error message, but it was not filtering properly

3. Wrapping the `List` from (example n.1) inside a `SimpleForm`
```tsx
<SimpleForm>
  <List filters={[<TextInput variant="outlined" placeholder="Example" label="City" source="city" 
  />]} />
</SimpleForm>
```

**Result** - did not work, also shows the `Cannot read properties of null (reading 'control')`

___
In conclusion, I tried a lot of use cases and it was not just reading the context properly, I even tried creating my own form to wrap the `List` within, (was chaotic) did not also work.

Also, I suspect that it might an issue from my setup but I am curious how is that possible, I have all the correct dependencies installed. 

## Note:
I am using yarn pnp. (updated the issue description)

**Comment by yousseftarekkh** [comment]
@fzaninotto

## Ticket Update
The issue is with PnP. I changed my `.yarnrc.yml`

### From

```yml
yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
    "@mui/styled-engine@*":
        dependencies:
            "@emotion/react": "*"
            "@emotion/styled": "*"
    "@mui/x-date-pickers@*":
        dependencies:
            "@babel/runtime": "*"
    ra-core@*:
        dependencies:
            connected-react-router: "*"
            history: <5
    ra-ui-materialui@*:
        dependencies:
            react-hook-form: "*"
    react-admin@*:
        dependencies:
            prop-types: "*"
            "@types/prop-types": "*"
        peerDependencies:
            "@types/react-router-dom": "*"

```

### To

```yml
yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
    # "@mui/styled-engine@*":
    #     dependencies:
    #         "@emotion/react": "*"
    #         "@emotion/styled": "*"
    # "@mui/x-date-pickers@*":
    #     dependencies:
    #         "@babel/runtime": "*"
    # ra-core@*:
    #     dependencies:
    #         connected-react-router: "*"
    #         history: <5
    # ra-ui-materialui@*:
    #     dependencies:
    #         react-hook-form: "*"
    # react-admin@*:
    #     dependencies:
    #         prop-types: "*"
    #         "@types/prop-types": "*"
    #     peerDependencies:
    #         "@types/react-router-dom": "*"

nodeLinker: node-modules
```

And it worked like charm. Any idea if my `.yarnrc.yml` should be optimized a little to make it work or simply React Admin was not tested with PnP?
